### ISSUE TITLE
"Waiting for refresh to finish..." but refresh never seems to finish

### ISSUE THREAD

**Issue by halbtuerke** [Malabarba/paradox#102]
I have a problem upgrading packages. I invoke `paradox-list-packages`, Paradox is connecting to the various package archives and listing the packages. The spinner in the mode-line mostly is still spinning.
When I then press `U` I get the message "Waiting for refresh to finish..." but it never finishes.

There's a `*Paradox http*` buffer with the following contents https://gist.github.com/halbtuerke/69182ce1ff1cbfb38617

This is what's in the `*Messages*` buffer
```
Overriding package-menu--print-info with paradox--print-info
Overriding package-menu--print-info-simple with paradox--print-info
Overriding package-menu--generate with paradox--generate-menu
Overriding package-menu-mode with paradox-menu-mode
Opening TLS connection to ‘marmalade-repo.org’...
Opening TLS connection with ‘gnutls-cli --insecure -p 443 marmalade-repo.org’...done
Opening TLS connection to ‘marmalade-repo.org’...done
Opening TLS connection to ‘raw.githubusercontent.com’...
Opening TLS connection with ‘gnutls-cli --insecure -p 443 raw.githubusercontent.com’...done
Opening TLS connection to ‘raw.githubusercontent.com’...done
Quit
Waiting for refresh to finish...
```

Spec:

Emacs 25.1.50 built 2015-11-27
OS X 10.11.1

Let me know if you need any more information.

Thanks in advance

**Comment by Malabarba** [comment]
I think this is due to a bug in package.el. It was fixed in the emacs-25 branch a couple of weeks ago, but I only just fixed it in master a few minutes ago.Try building from the emacs-25 branch (which would be a good thing to do anyway because that's where most of the development effort is ATM).

**Comment by halbtuerke** [comment]
Do you mean 8eaba112c952eecd5b7f17af40c29584a7172f59?

**Comment by Malabarba** [comment]
Yes.

**Comment by halbtuerke** [comment]
OK, will try. Takes a "couple" of minutes on my grand-daddy Mac... :D

**Comment by halbtuerke** [comment]
Updating to the emacs-25 branch did not fix the problem.

BUT I disabled GitHub integration via `(setq paradox-github-token t)` which seems to fix the problem.

**Comment by Malabarba** [comment]
Should be fixed now. Sorry for the delay.

**Comment by halbtuerke** [comment]
> Should be fixed now. Sorry for the delay.

Still not fixed with https://github.com/Malabarba/paradox/commit/d62d883b8c980d679970bed79c12091df9120a77 and GitHub integration enabled.

**Comment by Malabarba** [comment]
Try deleting paradox, restarting emacs, and installing again. The bug was in a macro so you might be getting old code.

**Comment by halbtuerke** [comment]
Ok, it now seems fixed but it takes quite a while. Maybe it has something to do with the number of stars I have on GitHub? The `*Paradox http*` buffer is going through my starred repos one page at a time which is quite slow:

```
Link: <https://api.github.com/user/starred?per_page=100&page=2>; rel="next", <https://api.github.com/user/starred?per_page=100&page=36>; rel="last"
```

**Comment by Malabarba** [comment]
Ah yes. That would explain the slowness. There's not much we can do about it, though. Github won't send more than 100 entries per page. 

I think the only option would be to just not fetch your list of starred packages. Most of the github functionality relies on your starred list, but at least you would still be able to star packages.

**Comment by halbtuerke** [comment]
Wouldn't it be possible to somehow cache the list of starred repos and only fetch the newly starred repos? 

[GitHub's API](https://developer.github.com/v3/activity/starring/#list-repositories-being-starred) has a parameter `sort => created (when the repository was starred)` for `GET /users/:username/starred`.

**Comment by Malabarba** [comment]
Yes. That sounds doable as well, although it'll require a whole caching system which paradox doesn't have yet. But is there a way to know which packages you've unstarred?

**Comment by halbtuerke** [comment]
> But is there a way to know which packages you've unstarred?

No, the API does not provide this information.

Is this even needed? When I star a repo I usually (read: never) won't unstar it in the future. That's why I have so many starred repos. ;)

**Comment by Malabarba** [comment]
No, it's not strictly needed. Just checking. :)
I'll leave this open in case someone wants to try to implement it. It's going to take me a while to get to it since I have quite a backlog. :(

**Comment by Malabarba** [comment]
Actually, I filed a new proper FR for this. So I'll close this issue for now.

**Comment by halbtuerke** [comment]
OK, thanks.
